In [1]:
from pytorch3d.utils import ico_sphere
from pytorch3d.io import load_obj, load_objs_as_meshes
from pytorch3d.structures import Meshes
from pytorch3d.ops import sample_points_from_meshes
from pytorch3d.loss import chamfer_distance

In [2]:
sphere_mesh = ico_sphere(level=3)
verts, faces, aux = load_obj('./data/cow_mesh/cow.obj')
test_mesh = Meshes(
    verts=[verts], 
    faces=[faces.verts_idx], 
)

sample_sphere = sample_points_from_meshes(sphere_mesh, 5000)
sample_test = sample_points_from_meshes(test_mesh, 5000)
loss_chamfer, _ = chamfer_distance(sample_sphere, sample_test)

In [3]:
import plotly.graph_objects as go
import numpy as np

In [4]:
fig = go.Figure(
    data=[go.Surface(
        z=verts[:, 2].numpy().tolist(),
        x=verts[:, 0].numpy().tolist(), 
        y=verts[:, 1].numpy().tolist(), 
    )]
)

fig.update_layout(
    title="a", 
    autosize=False, 
    width=500, 
    height=500,
    margin=dict(l=65, r=50, b=65, t=90),  
)

fig.show()


In [5]:
face_attribs = faces.__doc__.split('(')[1].split(')')[0].split(', ')
face_attribs

['verts_idx', 'normals_idx', 'textures_idx', 'materials_idx']

In [6]:
for idx, f_attrib in enumerate(face_attribs):
    attrib = getattr(faces, f_attrib)
    print(f_attrib, ':')
    print('type: ', type(attrib))
    print('size: ', attrib.size())
    print('value:')
    print(attrib, '\n')


verts_idx :
type:  <class 'torch.Tensor'>
size:  torch.Size([5856, 3])
value:
tensor([[ 738,  734,  735],
        [ 188,  735,  734],
        [ 191,  737,  736],
        ...,
        [1855,  107, 2929],
        [2927, 2929,  733],
        [2923,  733, 2929]]) 

normals_idx :
type:  <class 'torch.Tensor'>
size:  torch.Size([5856, 3])
value:
tensor([[-1, -1, -1],
        [-1, -1, -1],
        [-1, -1, -1],
        ...,
        [-1, -1, -1],
        [-1, -1, -1],
        [-1, -1, -1]]) 

textures_idx :
type:  <class 'torch.Tensor'>
size:  torch.Size([5856, 3])
value:
tensor([[   0,    1,    2],
        [   3,    2,    1],
        [   4,    5,    6],
        ...,
        [2777, 3221, 2776],
        [2773, 2776, 3224],
        [2769, 3224, 2776]]) 

materials_idx :
type:  <class 'torch.Tensor'>
size:  torch.Size([5856])
value:
tensor([0, 0, 0,  ..., 0, 0, 0]) 



In [7]:
aux_attribs = aux.__doc__.split('(')[1].split(')')[0].split(', ')
aux_attribs

['normals', 'verts_uvs', 'material_colors', 'texture_images', 'texture_atlas']

In [8]:
for idx, aux_attrib in enumerate(aux_attribs):
    attrib = getattr(aux, aux_attrib)
    print(aux_attrib, ':')
    print('type: ', type(attrib))
    if idx == 1:
        print('size: ', attrib.size())
    # print('size: ', aux_attrib.size())
    print('value:')
    print(attrib, '\n')

normals :
type:  <class 'NoneType'>
value:
None 

verts_uvs :
type:  <class 'torch.Tensor'>
size:  torch.Size([3225, 2])
value:
tensor([[0.8004, 0.6675],
        [0.7896, 0.6682],
        [0.7999, 0.6639],
        ...,
        [0.5429, 0.3197],
        [0.4766, 0.3259],
        [0.4950, 0.2872]]) 

material_colors :
type:  <class 'dict'>
value:
{'material_1': {'ambient_color': tensor([1., 1., 1.]), 'diffuse_color': tensor([1., 1., 1.]), 'specular_color': tensor([0., 0., 0.]), 'shininess': tensor([10.])}} 

texture_images :
type:  <class 'dict'>
value:
{'material_1': tensor([[[1.0000, 0.9333, 0.9020],
         [1.0000, 0.9333, 0.9020],
         [1.0000, 0.9333, 0.9020],
         ...,
         [1.0000, 0.9333, 0.9020],
         [1.0000, 0.9333, 0.9020],
         [1.0000, 0.9333, 0.9020]],

        [[1.0000, 0.9333, 0.9020],
         [1.0000, 0.9333, 0.9020],
         [1.0000, 0.9333, 0.9020],
         ...,
         [1.0000, 0.9333, 0.9020],
         [1.0000, 0.9333, 0.9020],
         [1.

In [9]:
verts_uvs = aux.verts_uvs[None, ...]
verts_uvs.size()

torch.Size([1, 3225, 2])